### ISSUE TITLE
MEC Dev branch doesn't build on macOS Catalina

### ISSUE THREAD

**Issue by NothanUmber** [TheTechnobear/MEC#21]
The current dev branch seems to have problems with macOS Catalina, looks like some new security stuff on first sight. The master branch builds fine though and works on first sight (tested with Alpha).

**To Reproduce**
build MEC as described in the BUILD file (the Mac variant with Xcode)

**Expected behavior**
build should succeed

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2

**Additional context**
Error message:
RegisterExecutionPolicyException /Users/ferdinand/git/mecdev/MEC/build/release/lib/MinSizeRel/libmec-push2.dylib (in target 'mec-push2' from project 'mec')
    cd /Users/ferdinand/git/mecdev/MEC
    builtin-RegisterExecutionPolicyException /Users/ferdinand/git/mecdev/MEC/build/release/lib/MinSizeRel/libmec-push2.dylib
note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'mec-push2' from project 'mec')

WriteAuxiliaryFile /Users/ferdinand/git/mecdev/MEC/build/mec-api/mec.build/MinSizeRel/mec-api.build/Objects-normal/x86_64/mec-api.LinkFileList (in target 'mec-api' from project 'mec')
    cd /Users/ferdinand/git/mecdev/MEC
    write-file /Users/ferdinand/git/mecdev/MEC/build/mec-api/mec.build/MinSizeRel/mec-api.build/Objects-normal/x86_64/mec-api.LinkFileList

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/ferdinand/git/mecdev/MEC/build/mec-api/mec.build/MinSizeRel/mec-api.build/Objects-normal/x86_64/mec_eigenharp.o /Users/ferdinand/git/mecdev/MEC/mec-api/devices/mec_eigenharp.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by NothanUmber** [comment]
P.S.: If I disable building the Push lib I get a similar error for the next dynlib, seems to be a systematic issue.

**Comment by TheTechnobear** [comment]
thats an odd error, and I cannot think off-hand what ive changed between master and dev that would affect this... 
only thing i can think, is something to do with using more dylibs, but Im pretty sure master branch also used some dylibs, so why different on dev?

a quick google, reveals it happening on other projects.
https://forums.developer.apple.com/thread/124529

unfortunately, Ive not seen a solution yet...

Ive not upgraded to catalina yet, and not sure when I will do it.... I guess its becoming more a priority.. but im pretty busy this side of the holidays.
but once I do, I'll find a way to fix it ;) 

if you find a fix in the meantime, please feel free to submit a PR.

note: we need it backwards compatible prior to 10.15 i think... as still lots of people are holding off upgrading to catalina, as so many apps/drivers are still not supporting catalina :(

**Comment by NothanUmber** [comment]
The error message above is misleading, the RegisterPolicyExecution problem is only a warning that also comes when building master.
The real issue is:

/Users/ferdinand/git/mecdev/MEC/mec-api/devices/mec_eigenharp.cpp:238:14: error: no member named
      'setPollTime' in 'EigenApi::Eigenharp'
    eigenD_->setPollTime(minPollTime_);
    ~~~~~~~  ^
/Users/ferdinand/git/mecdev/MEC/mec-api/devices/mec_eigenharp.cpp:256:27: error: no member named 'process'
      in 'EigenApi::Eigenharp'
    if (active_) eigenD_->process();
                 ~~~~~~~  ^
3 warnings and 2 errors generated.

The reason for that is that "git checkout dev" doesn't seem to update the submodules to the referenced versions automatically. I had to do "git submodule update --recursive" additional to the checkout, now dev builds as expected.
Sorry, should have checked the error message more closely.

**Comment by TheTechnobear** [comment]
Yeah submodules always needs to be updated as an additional step.  
But good to know about the red herring message ,  we are bound to see it again :)
